[package]
name = "capitalize"
description = "Change first character to upper case and the rest to lower case"
version = "0.1.0"
edition = "2021"
authors = ["Jesus Hernandez <jesushdez@protonmail.com>"]
license = "Unlicense"
